spring:
  config:
    activate:
      on-profile: test
name: test-YAML
environment: testing
---
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
environment: production
user: wZ92DKv1mUlqRqWi2lYgGgeXYAhdOciUtx69Pdu10Aw=
contra: AVO1DfKzz4HR99XciLi4CDzy6nCIab53UqDGJoeGlYY=